### ISSUE TITLE
We are going to use a new tool

### ISSUE THREAD

**Issue by OIMA** [OIMA/linux_performance_analysis#39]
We need to automate some important things on server's side. We are going to use a tool called **expect**. Please write a shell script for this installation and append it on [install_packages.sh](https://github.com/OIMA/linux_performance_analysis/blob/master/scripts/install_packages.sh).

You can follow this [tutorial](http://linuxnextgen.blogspot.mx/2011/11/install-expect-in-linux.html) to start.

**Comment by jglezt** [comment]
Done, Time to close this issue.
